### ISSUE TITLE
500 error when try to search a name

### ISSUE THREAD

**Issue by xjabr** [jensbrehmen/xeerio#2]
<img width="1792" alt="Screenshot 2020-12-22 at 15 45 36" src="https://user-images.githubusercontent.com/29646226/102900635-da9fe200-446c-11eb-9962-aa918009c449.png">
<img width="1792" alt="Screenshot 2020-12-22 at 15 45 33" src="https://user-images.githubusercontent.com/29646226/102900653-e4294a00-446c-11eb-8be3-869fd90a4d69.png">
<img width="1792" alt="Screenshot 2020-12-22 at 15 45 28" src="https://user-images.githubusercontent.com/29646226/102900679-ec818500-446c-11eb-8b8f-70a71e200be9.png">

**Comment by jensbrehmen** [comment]
Hi, thank you for letting me know, this should be fixed by now. I only have some issues capturing the country code of the visitor while using Digital Ocean's app platform to host the app, I might need to switch to a custom server.

**Comment by xjabr** [comment]
ok, good work and the project is very cool
